import { publicPath } from "@/lib/public-path";
import type { AudioSource, StoryAudio } from "./types";

/**
 * Audio configuration.
 *
 * No narration has been recorded yet. Until it is, every story points at a
 * synthesised tanpura-style ambient track (generated by
 * scripts/generate-demo-audio.sh) so the player can be exercised end to end.
 * The UI labels these sources as demo audio.
 *
 * To add real narration: drop files in /public/audio/<story-slug>/ and add an
 * entry to NARRATION below, e.g.
 *
 *   "birth-of-karna": {
 *     en: { src: "/audio/birth-of-karna/en.mp3", kind: "narration", narrator: "…" },
 *     te: { src: "/audio/birth-of-karna/te.mp3", kind: "narration", narrator: "…" },
 *   },
 */

export const DEMO_AUDIO: Required<StoryAudio> = {
  en: { src: "/audio/demo/ambient-en.mp3", durationSec: 150, kind: "demo" },
  te: { src: "/audio/demo/ambient-te.mp3", durationSec: 150, kind: "demo" },
};

const NARRATION: Record<string, StoryAudio> = {};

/** Audio for a story: recorded narration where it exists, demo audio otherwise. */
export function audioForStory(slug: string): StoryAudio {
  const recorded = NARRATION[slug] ?? {};
  const resolve = (source: AudioSource): AudioSource => ({ ...source, src: publicPath(source.src) });
  return {
    en: resolve(recorded.en ?? DEMO_AUDIO.en),
    te: resolve(recorded.te ?? DEMO_AUDIO.te),
  };
}

export function isDemoAudio(source: AudioSource | undefined): boolean {
  return !source || source.kind === "demo";
}
